language: java

env:
  global:
    - MAVEN_OPTS="-Xmx2g -XX:+ExitOnOutOfMemoryError"
    - MAVEN_SKIP_CHECKS_AND_DOCS="-Dair.check.skip-all=true -Dmaven.javadoc.skip=true"

sudo: required
dist: trusty

install: travis_wait 30 mvn install

cache:
  directories:
    - $HOME/.m2/repository

services:
  - docker

install:
  - mvn -v

script:
  mvn install -DskipTests

before_cache:
  # Make the cache stable between builds by removing build output
  - rm -rf $HOME/.m2/repository/com/facebook
