title: Hexo-docs
subtitle: "快捷建设你的官网平台"
description: "快捷建设你的官网平台"
language:
- en
- zh-cn
timezone: UTC
url: https://harbby.github.io/project/sylph
# 文件路径
root: /project/sylph
archive_dir: news
permalink: news/:year/:month/:day/:title/
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: docs

less:
  compress: true

# 忽略的文件，开始匹配的目录是source目录
skip_render:
  - ci.yml
  - README.md
